In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/house-prices-prediction/sample_submission.csv
/kaggle/input/house-prices-prediction/data_description.txt
/kaggle/input/house-prices-prediction/train.csv
/kaggle/input/house-prices-prediction/test.csv


# Create a Dataframe containing the data set

In [2]:
df_train = pd.read_csv('/kaggle/input/house-prices-prediction/test.csv')
df_test = pd.read_csv('/kaggle/input/house-prices-prediction/test.csv')
df_sample_submission = pd.read_csv('/kaggle/input/house-prices-prediction/sample_submission.csv')

# Look up the Train Dataset

In [3]:
df_train.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [4]:
df_train.shape

(1459, 80)

In [5]:
df_train.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

# Look up the Test Dataset

In [6]:
df_test.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [7]:
df_test.shape

(1459, 80)

In [8]:
df_test.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

# Look up the sample submission containing the predicting value

In [9]:
df_sample_submission.head()

Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977

In [10]:
df_sample_submission.shape

(1459, 2)

In [11]:
df_sample_submission.columns

Index(['Id', 'SalePrice'], dtype='object')

# NaN Value Handling

In [12]:
df_train = df_train.fillna(0)

# Simple Linear Regression With scikit-learn

## Import Linear Regression Module

In [13]:
from sklearn.linear_model import LinearRegression

## Provide the input Variables

In [14]:
x_lotArea = np.array([df_train['LotArea']]).reshape((-1, 1))
x_lotFrontage = np.array([df_train['LotFrontage']]).reshape((-1, 1))
x_msSubClass = np.array([df_train['MSSubClass']]).reshape((-1, 1))
x_overallQual = np.array([df_train['OverallQual']]).reshape(-1, 1)
x_overallCond = np.array([df_train['OverallCond']]).reshape(-1, 1)
y_salePrice = np.array([df_sample_submission['SalePrice']]).reshape((-1, 1))

## Create a Model and fit it

In [15]:
model_lotArea = LinearRegression().fit(x_lotArea, y_salePrice)
model_lotFrontage = LinearRegression().fit(x_lotFrontage, y_salePrice)
model_msSubClass = LinearRegression().fit(x_msSubClass, y_salePrice)
model_overallQual = LinearRegression().fit(x_overallQual, y_salePrice)
model_overallCond = LinearRegression().fit(x_overallCond, y_salePrice)

## Get results

In [16]:
r_sq_lotArea = model_lotArea.score(x_lotArea, y_salePrice)
r_sq_lotFrontage = model_lotFrontage.score(x_lotFrontage, y_salePrice)
r_sq_msSubClass = model_msSubClass.score(x_msSubClass, y_salePrice)
r_sq_overallQual = model_overallQual.score(x_overallQual, y_salePrice)
r_sq_overallCond = model_overallCond.score(x_overallCond, y_salePrice)

dict_features = {'LotArea':r_sq_lotArea, 'LotFrontage':r_sq_lotFrontage, 'MSSubClass': r_sq_msSubClass, 'OverallQual':r_sq_overallQual, 'OverallCond':r_sq_overallCond}
for feature, score in dict_features.items():
    print(f"Input Feature: {feature}")
    print(f"coefficient of determination: {score}")
    print("===============================================================")

Input Feature: LotArea
coefficient of determination: 0.5123629952730855
Input Feature: LotFrontage
coefficient of determination: 0.03486342370470641
Input Feature: MSSubClass
coefficient of determination: 0.04240173426407168
Input Feature: OverallQual
coefficient of determination: 0.008769092824928881
Input Feature: OverallCond
coefficient of determination: 0.007014545671814809


## Predict the response

In [17]:
y_pred_lotArea = model_lotArea.predict(x_lotArea)
y_pred_lotFrontage = model_lotFrontage.predict(x_lotFrontage)
y_pred_msSubClass = model_msSubClass.predict(x_msSubClass)
y_pred_overallQual = model_overallQual.predict(x_overallQual)
y_pred_overallCond = model_overallCond.predict(x_overallCond)

print(f"predicted response with LotArea as input: \n{y_pred_lotArea}")
print(f"predicted response with LotFrontage as input: \n{y_pred_lotFrontage}")
print(f"predicted response with MSSubClass as input: \n{y_pred_msSubClass}")
print(f"predicted response with OverallQual as input: \n{y_pred_overallQual}")
print(f"predicted response with OverallCond as input: \n{y_pred_overallCond}")

predicted response with LotArea as input: 
[[183485.44111251]
 [189796.33655443]
 [188753.66687273]
 ...
 [203475.11295086]
 [180667.6084029 ]
 [178725.42734819]]
predicted response with LotFrontage as input: 
[[181295.44275988]
 [181391.0310273 ]
 [180721.91315537]
 ...
 [188942.50415335]
 [179574.85394635]
 [180721.91315537]]
predicted response with MSSubClass as input: 
[[182158.13658041]
 [182158.13658041]
 [178975.31119871]
 ...
 [182158.13658041]
 [176986.04533515]
 [178975.31119871]]
predicted response with OverallQual as input: 
[[178022.49005643]
 [179099.06167251]
 [178022.49005643]
 ...
 [178022.49005643]
 [178022.49005643]
 [180175.6332886 ]]
predicted response with OverallCond as input: 
[[178629.66628348]
 [178629.66628348]
 [179871.83772502]
 ...
 [177387.49484194]
 [179871.83772502]
 [179871.83772502]]
