In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/house-prices-prediction/sample_submission.csv
/kaggle/input/house-prices-prediction/data_description.txt
/kaggle/input/house-prices-prediction/train.csv
/kaggle/input/house-prices-prediction/test.csv


# Create a Dataframe containing the data set

In [2]:
df_train = pd.read_csv('/kaggle/input/house-prices-prediction/test.csv')
df_test = pd.read_csv('/kaggle/input/house-prices-prediction/test.csv')
df_sample_submission = pd.read_csv('/kaggle/input/house-prices-prediction/sample_submission.csv')

# Look up the Train Dataset

In [3]:
df_train.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [4]:
df_train.shape

(1459, 80)

In [5]:
df_train.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

# Look up the Test Dataset

In [6]:
df_test.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [7]:
df_test.shape

(1459, 80)

In [8]:
df_test.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

# Look up the sample submission containing the predicting value

In [9]:
df_sample_submission.head()

Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977

In [10]:
df_sample_submission.shape

(1459, 2)

In [11]:
df_sample_submission.columns

Index(['Id', 'SalePrice'], dtype='object')

# NaN Value Handling

In [12]:
df_train = df_train.fillna(0)

# Simple Linear Regression With scikit-learn

## Import Linear Regression Module

In [13]:
from sklearn.linear_model import LinearRegression

## Provide the input Variables

In [14]:
x_lotArea = np.array([df_train['LotArea']]).reshape((-1, 1))
x_lotFrontage = np.array([df_train['LotFrontage']]).reshape((-1, 1))
x_msSubClass = np.array([df_train['MSSubClass']]).reshape((-1, 1))
x_overallQual = np.array([df_train['OverallQual']]).reshape(-1, 1)
x_overallCond = np.array([df_train['OverallCond']]).reshape(-1, 1)
y_salePrice = np.array([df_sample_submission['SalePrice']]).reshape((-1, 1))

## Create a Model and fit it

In [15]:
model_lotArea = LinearRegression().fit(x_lotArea, y_salePrice)
model_lotFrontage = LinearRegression().fit(x_lotFrontage, y_salePrice)
model_msSubClass = LinearRegression().fit(x_msSubClass, y_salePrice)
model_overallQual = LinearRegression().fit(x_overallQual, y_salePrice)
model_overallCond = LinearRegression().fit(x_overallCond, y_salePrice)

## Get results

In [16]:
r_sq_lotArea = model_lotArea.score(x_lotArea, y_salePrice)
r_sq_lotFrontage = model_lotFrontage.score(x_lotFrontage, y_salePrice)
r_sq_msSubClass = model_msSubClass.score(x_msSubClass, y_salePrice)
r_sq_overallQual = model_overallQual.score(x_overallQual, y_salePrice)
r_sq_overallCond = model_overallCond.score(x_overallCond, y_salePrice)

dict_features = {'LotArea':r_sq_lotArea, 'LotFrontage':r_sq_lotFrontage, 'MSSubClass': r_sq_msSubClass, 'OverallQual':r_sq_overallQual, 'OverallCond':r_sq_overallCond}
for feature, score in dict_features.items():
    print(f"Input Feature: {feature}")
    print(f"coefficient of determination: {score}")
    print("===============================================================")

Input Feature: LotArea
coefficient of determination: 0.5123629952730855
Input Feature: LotFrontage
coefficient of determination: 0.03486342370470641
Input Feature: MSSubClass
coefficient of determination: 0.04240173426407168
Input Feature: OverallQual
coefficient of determination: 0.008769092824928881
Input Feature: OverallCond
coefficient of determination: 0.007014545671814809


## Predict the response

In [17]:
y_pred_lotArea = model_lotArea.predict(x_lotArea)
y_pred_lotFrontage = model_lotFrontage.predict(x_lotFrontage)
y_pred_msSubClass = model_msSubClass.predict(x_msSubClass)
y_pred_overallQual = model_overallQual.predict(x_overallQual)
y_pred_overallCond = model_overallCond.predict(x_overallCond)

print(f"predicted response with LotArea as input: \n{y_pred_lotArea}\n")
print(f"predicted response with LotFrontage as input: \n{y_pred_lotFrontage}\n")
print(f"predicted response with MSSubClass as input: \n{y_pred_msSubClass}\n")
print(f"predicted response with OverallQual as input: \n{y_pred_overallQual}\n")
print(f"predicted response with OverallCond as input: \n{y_pred_overallCond}\n")

predicted response with LotArea as input: 
[[183485.44111251]
 [189796.33655443]
 [188753.66687273]
 ...
 [203475.11295086]
 [180667.6084029 ]
 [178725.42734819]]

predicted response with LotFrontage as input: 
[[181295.44275988]
 [181391.0310273 ]
 [180721.91315537]
 ...
 [188942.50415335]
 [179574.85394635]
 [180721.91315537]]

predicted response with MSSubClass as input: 
[[182158.13658041]
 [182158.13658041]
 [178975.31119871]
 ...
 [182158.13658041]
 [176986.04533515]
 [178975.31119871]]

predicted response with OverallQual as input: 
[[178022.49005643]
 [179099.06167251]
 [178022.49005643]
 ...
 [178022.49005643]
 [178022.49005643]
 [180175.6332886 ]]

predicted response with OverallCond as input: 
[[178629.66628348]
 [178629.66628348]
 [179871.83772502]
 ...
 [177387.49484194]
 [179871.83772502]
 [179871.83772502]]



# Multiple Linear Regression

## Import necessary modules

In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression

## Provide the input variables

In [19]:
x_lotArea_lotFrontage = np.array([df_train[['LotArea', 'LotFrontage']]]).reshape((-1, 2))
x_lotArea_msSubClass = np.array([df_train[['LotArea', 'MSSubClass']]]).reshape((-1, 2))
x_lotArea_overallQual = np.array([df_train[['LotArea', 'OverallQual']]]).reshape((-1, 2))
x_lotArea_overallCond = np.array([df_train[['LotArea', 'OverallCond']]]).reshape((-1, 2))
x_lotFrontage_msSubClass = np.array([df_train[['LotFrontage', 'MSSubClass']]]).reshape((-1, 2))
x_lotFrontage_overallQual = np.array([df_train[['LotFrontage', 'OverallQual']]]).reshape((-1, 2))
x_lotFrontage_overallCond = np.array([df_train[['LotFrontage', 'OverallCond']]]).reshape((-1, 2))
x_msSubClass_overallQual = np.array([df_train[['MSSubClass', 'OverallQual']]]).reshape((-1, 2))
x_msSubClass_overallCond = np.array([df_train[['MSSubClass', 'OverallCond']]]).reshape((-1, 2))
x_overallQual_overallCond = np.array([df_train[['OverallQual', 'OverallCond']]]).reshape((-1, 2))

# y_salePrice = np.array([df_sample_submission['SalePrice']]).reshape((-1, 1))

## Inspect the x input variables

In [20]:
print(f"LotArea and LotFrontage: \n{x_lotArea_lotFrontage}\n")
print(f"LotArea and MSSubClass: \n{x_lotArea_msSubClass}\n")
print(f"LotArea and OverallQual: \n{x_lotArea_overallQual}\n")
print(f"LotArea and OverallCond: \n{x_lotArea_overallCond}\n")
print(f"LotFrontage and MSSubClass: \n{x_lotFrontage_msSubClass}\n")
print(f"LotFrontage and OverallQual: \n{x_lotFrontage_overallQual}\n")
print(f"LotFrontage and OverallCond: \n{x_lotFrontage_overallCond}\n")
print(f"MSSubClass and OverallQual: \n{x_msSubClass_overallQual}\n")
print(f"MSSubClass and OverallCond: \n{x_msSubClass_overallCond}\n")
print(f"OverallQual and OverallCond: \n{x_overallQual_overallCond}\n")

LotArea and LotFrontage: 
[[11622.    80.]
 [14267.    81.]
 [13830.    74.]
 ...
 [20000.   160.]
 [10441.    62.]
 [ 9627.    74.]]

LotArea and MSSubClass: 
[[11622    20]
 [14267    20]
 [13830    60]
 ...
 [20000    20]
 [10441    85]
 [ 9627    60]]

LotArea and OverallQual: 
[[11622     5]
 [14267     6]
 [13830     5]
 ...
 [20000     5]
 [10441     5]
 [ 9627     7]]

LotArea and OverallCond: 
[[11622     6]
 [14267     6]
 [13830     5]
 ...
 [20000     7]
 [10441     5]
 [ 9627     5]]

LotFrontage and MSSubClass: 
[[ 80.  20.]
 [ 81.  20.]
 [ 74.  60.]
 ...
 [160.  20.]
 [ 62.  85.]
 [ 74.  60.]]

LotFrontage and OverallQual: 
[[ 80.   5.]
 [ 81.   6.]
 [ 74.   5.]
 ...
 [160.   5.]
 [ 62.   5.]
 [ 74.   7.]]

LotFrontage and OverallCond: 
[[ 80.   6.]
 [ 81.   6.]
 [ 74.   5.]
 ...
 [160.   7.]
 [ 62.   5.]
 [ 74.   5.]]

MSSubClass and OverallQual: 
[[20  5]
 [20  6]
 [60  5]
 ...
 [20  5]
 [85  5]
 [60  7]]

MSSubClass and OverallCond: 
[[20  6]
 [20  6]
 [60  5]
 ...
 [

## Create a multilinear model and fit it

In [21]:
model_lotArea_lotFrontage = LinearRegression().fit(x_lotArea_lotFrontage, y_salePrice)
model_lotArea_msSubClass = LinearRegression().fit(x_lotArea_msSubClass, y_salePrice)
model_lotArea_overallQual = LinearRegression().fit(x_lotArea_overallQual, y_salePrice)
model_lotArea_overallCond = LinearRegression().fit(x_lotArea_overallCond, y_salePrice)

model_lotFrontage_msSubClass = LinearRegression().fit(x_lotFrontage_msSubClass, y_salePrice)
model_lotFrontage_overallQual = LinearRegression().fit(x_lotFrontage_overallQual, y_salePrice)
model_lotFrontage_overallCond = LinearRegression().fit(x_lotFrontage_overallCond, y_salePrice)

model_msSubClass_overallQual = LinearRegression().fit(x_msSubClass_overallQual, y_salePrice)
model_msSubClass_overallCond = LinearRegression().fit(x_msSubClass_overallCond, y_salePrice)

model_overallQual_overallCond = LinearRegression().fit(x_overallQual_overallCond, y_salePrice)

## Get results

In [22]:
r_sq_lotArea_lotFrontage = model_lotArea_lotFrontage.score(x_lotArea_lotFrontage, y_salePrice)
r_sq_lotArea_msSubClass = model_lotArea_msSubClass.score(x_lotArea_msSubClass, y_salePrice)
r_sq_lotArea_overallQual = model_lotArea_overallQual.score(x_lotArea_overallQual, y_salePrice)
r_sq_lotArea_overallCond = model_lotArea_overallCond.score(x_lotArea_overallCond, y_salePrice)

r_sq_lotFrontage_msSubClass = model_lotFrontage_msSubClass.score(x_lotFrontage_msSubClass, y_salePrice)
r_sq_lotFrontage_overallQual = model_lotFrontage_overallQual.score(x_lotFrontage_overallQual, y_salePrice)
r_sq_lotFrontage_overallCond = model_lotFrontage_overallCond.score(x_lotFrontage_overallCond, y_salePrice)

r_sq_msSubClass_overallQual = model_msSubClass_overallQual.score(x_msSubClass_overallQual, y_salePrice)
r_sq_msSubClass_overallCond = model_msSubClass_overallCond.score(x_msSubClass_overallCond, y_salePrice)

r_sq_overallQual_overallCond = model_overallQual_overallCond.score(x_overallQual_overallCond, y_salePrice)

dict_features = {'LotArea and LotFrontage':r_sq_lotArea_lotFrontage, 
                 'LotArea and MSSubClass':r_sq_lotArea_msSubClass, 
                 'LotArea and OverallQual':r_sq_lotArea_overallQual, 
                 'LotArea and OverallCond':r_sq_lotArea_overallCond, 
                 'LotFrontage and MSSubClass':r_sq_lotFrontage_msSubClass, 
                 'LotFrontage and OverallQual':r_sq_lotFrontage_overallQual, 
                 'LotFrontage and OverallCond':r_sq_lotFrontage_overallCond, 
                 'MSSubClass and OverallQual':r_sq_msSubClass_overallQual,
                 'MSSubClass and OverallCond':r_sq_msSubClass_overallCond, 
                 'OverallQual and OverallCond':r_sq_overallQual_overallCond}
for duo_feature, score in dict_features.items():
    print(f"Input Feature: {duo_feature}")
    print(f"coefficient of determination: {score}")
    print("===============================================================")

Input Feature: LotArea and LotFrontage
coefficient of determination: 0.5128940223745833
Input Feature: LotArea and MSSubClass
coefficient of determination: 0.515401669427938
Input Feature: LotArea and OverallQual
coefficient of determination: 0.5126333129216907
Input Feature: LotArea and OverallCond
coefficient of determination: 0.5124588589872286
Input Feature: LotFrontage and MSSubClass
coefficient of determination: 0.0621055520398438
Input Feature: LotFrontage and OverallQual
coefficient of determination: 0.04088116942415998
Input Feature: LotFrontage and OverallCond
coefficient of determination: 0.0413361542178583
Input Feature: MSSubClass and OverallQual
coefficient of determination: 0.05257194312346136
Input Feature: MSSubClass and OverallCond
coefficient of determination: 0.05216038738153139
Input Feature: OverallQual and OverallCond
coefficient of determination: 0.014412252186155938


## Predict the response for considering two input features

In [23]:
y_pred_lotArea_lotFrontage = model_lotArea_lotFrontage.predict(x_lotArea_lotFrontage)
y_pred_lotArea_msSubClass = model_lotArea_msSubClass.predict(x_lotArea_msSubClass)
y_pred_lotArea_overallQual = model_lotArea_overallQual.predict(x_lotArea_overallQual)
y_pred_lotArea_overallCond = model_lotArea_overallCond.predict(x_lotArea_overallCond)

y_pred_lotFrontage_msSubClass = model_lotFrontage_msSubClass.predict(x_lotFrontage_msSubClass)
y_pred_lotFrontage_overallQual = model_lotFrontage_overallQual.predict(x_lotFrontage_overallQual)
y_pred_lotFrontage_overallCond = model_lotFrontage_overallCond.predict(x_lotFrontage_overallCond)

y_pred_msSubClass_overallQual = model_msSubClass_overallQual.predict(x_msSubClass_overallQual)
y_pred_msSubClass_overallCond = model_msSubClass_overallCond.predict(x_msSubClass_overallCond)

y_pred_overallQual_overallCond = model_overallQual_overallCond.predict(x_overallQual_overallCond)

print(f"predicted response with LotArea and Lot Frontage as input: \n{y_pred_lotArea_lotFrontage}\n")
print(f"predicted response with LotArea and MSSubClass as input: \n{y_pred_lotArea_msSubClass}\n")
print(f"predicted response with LotArea and OverallQual as input: \n{y_pred_lotArea_overallQual}\n")
print(f"predicted response with LotArea and OverallCond as input: \n{y_pred_lotArea_overallCond}\n")

print(f"predicted response with Lot Frontage and MSSubClass as input: \n{y_pred_lotFrontage_msSubClass}\n")
print(f"predicted response with Lot Frontage and OverallQual as input: \n{y_pred_lotFrontage_overallQual}\n")
print(f"predicted response with Lot Frontage and OverallQual as input: \n{y_pred_lotFrontage_overallCond}\n")

print(f"predicted response with MSSubClass and OverallQual as input: \n{y_pred_msSubClass_overallQual}\n")
print(f"predicted response with MSSubClass and OverallCond as input: \n{y_pred_msSubClass_overallCond}\n")

print(f"predicted response with OverallQual and OverallCond as input: \n{y_pred_overallQual_overallCond}\n")

predicted response with LotArea and Lot Frontage as input: 
[[183720.52989267]
 [189995.635597  ]
 [188876.03634239]
 ...
 [204528.10558872]
 [180705.91593207]
 [178923.92829614]]

predicted response with LotArea and MSSubClass as input: 
[[182759.81969211]
 [189257.97519109]
 [189097.47147067]
 ...
 [203342.63510628]
 [181342.16977759]
 [178771.66898968]]

predicted response with LotArea and OverallQual as input: 
[[183269.59273119]
 [189754.87198856]
 [188524.67409557]
 ...
 [203209.38968352]
 [180458.79060649]
 [178901.71476972]]

predicted response with LotArea and OverallCond as input: 
[[183414.18118963]
 [189716.10253805]
 [188820.91225524]
 ...
 [203229.43099146]
 [180746.3521608 ]
 [178806.9328876 ]]

predicted response with Lot Frontage and MSSubClass as input: 
[[183281.2356805 ]
 [183355.37585321]
 [180204.30698275]
 ...
 [189212.44949747]
 [177669.57012178]
 [180204.30698275]]

predicted response with Lot Frontage and OverallQual as input: 
[[180252.39949856]
 [181239.7703

# Polynomial Regression

## Import necessary modules

In [24]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

## Provide input features

In [25]:
x_lotArea = np.array([df_train['LotArea']]).reshape((-1, 1))
x_lotFrontage = np.array([df_train['LotFrontage']]).reshape((-1, 1))
x_msSubClass = np.array([df_train['MSSubClass']]).reshape((-1, 1))
x_overallQual = np.array([df_train['OverallQual']]).reshape(-1, 1)
x_overallCond = np.array([df_train['OverallCond']]).reshape(-1, 1)
y_salePrice = np.array([df_sample_submission['SalePrice']]).reshape((-1, 1))

## Transform input data

In [26]:
x_lotArea = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x_lotArea)
x_lotFrontage = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x_lotFrontage)
x_msSubClass = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x_msSubClass)
x_overallQual = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x_overallQual)
x_overallCond = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x_overallCond)

transformer_list = [x_lotArea, x_lotFrontage, x_msSubClass, x_overallQual, x_overallCond]
transformer_list

[array([[1.16220000e+04, 1.35070884e+08],
        [1.42670000e+04, 2.03547289e+08],
        [1.38300000e+04, 1.91268900e+08],
        ...,
        [2.00000000e+04, 4.00000000e+08],
        [1.04410000e+04, 1.09014481e+08],
        [9.62700000e+03, 9.26791290e+07]]),
 array([[   80.,  6400.],
        [   81.,  6561.],
        [   74.,  5476.],
        ...,
        [  160., 25600.],
        [   62.,  3844.],
        [   74.,  5476.]]),
 array([[  20.,  400.],
        [  20.,  400.],
        [  60., 3600.],
        ...,
        [  20.,  400.],
        [  85., 7225.],
        [  60., 3600.]]),
 array([[ 5., 25.],
        [ 6., 36.],
        [ 5., 25.],
        ...,
        [ 5., 25.],
        [ 5., 25.],
        [ 7., 49.]]),
 array([[ 6., 36.],
        [ 6., 36.],
        [ 5., 25.],
        ...,
        [ 7., 49.],
        [ 5., 25.],
        [ 5., 25.]])]

## Create a Model and fit it

In [27]:
model_lotArea = LinearRegression().fit(x_lotArea, y_salePrice)
model_lotFrontage = LinearRegression().fit(x_lotFrontage, y_salePrice)
model_msSubClass = LinearRegression().fit(x_msSubClass, y_salePrice)
model_overallQual = LinearRegression().fit(x_overallQual, y_salePrice)
model_overallCond = LinearRegression().fit(x_overallCond, y_salePrice)

## Get results

In [28]:
r_sq_lotArea = model_lotArea.score(x_lotArea, y_salePrice)
r_sq_lotFrontage = model_lotFrontage.score(x_lotFrontage, y_salePrice)
r_sq_msSubClass = model_msSubClass.score(x_msSubClass, y_salePrice)
r_sq_overallQual = model_overallQual.score(x_overallQual, y_salePrice)
r_sq_overallCond = model_overallCond.score(x_overallCond, y_salePrice)

dict_features = {'LotArea':r_sq_lotArea, 'LotFrontage':r_sq_lotFrontage, 'MSSubClass': r_sq_msSubClass, 'OverallQual':r_sq_overallQual, 'OverallCond':r_sq_overallCond}
for feature, score in dict_features.items():
    print(f"Input Feature: {feature}")
    print(f"coefficient of determination: {score}")
    print("===============================================================")

Input Feature: LotArea
coefficient of determination: 0.5202549233183307
Input Feature: LotFrontage
coefficient of determination: 0.1331497860212988
Input Feature: MSSubClass
coefficient of determination: 0.06035064062190987
Input Feature: OverallQual
coefficient of determination: 0.009571097339512669
Input Feature: OverallCond
coefficient of determination: 0.011088314171518898


## Predict a Response

In [29]:
y_pred_lotArea = model_lotArea.predict(x_lotArea)
y_pred_lotFrontage = model_lotFrontage.predict(x_lotFrontage)
y_pred_msSubClass = model_msSubClass.predict(x_msSubClass)
y_pred_overallQual = model_overallQual.predict(x_overallQual)
y_pred_overallCond = model_overallCond.predict(x_overallCond)

print(f"predicted response with LotArea as input: \n{y_pred_lotArea}\n")
print(f"predicted response with LotFrontage as input: \n{y_pred_lotFrontage}\n")
print(f"predicted response with MSSubClass as input: \n{y_pred_msSubClass}\n")
print(f"predicted response with OverallQual as input: \n{y_pred_overallQual}\n")
print(f"predicted response with OverallCond as input: \n{y_pred_overallCond}\n")

predicted response with LotArea as input: 
[[184299.60283635]
 [191012.62873535]
 [189919.52517816]
 ...
 [204766.30886432]
 [181227.26768783]
 [179082.7350444 ]]

predicted response with LotFrontage as input: 
[[180099.16038619]
 [180378.83347327]
 [178563.68359076]
 ...
 [223925.15295217]
 [176225.90459633]
 [178563.68359076]]

predicted response with MSSubClass as input: 
[[180473.81314391]
 [180473.81314391]
 [180904.44940935]
 ...
 [180473.81314391]
 [179582.20896376]
 [180904.44940935]]

predicted response with OverallQual as input: 
[[178121.63787662]
 [179425.39554932]
 [178121.63787662]
 ...
 [178121.63787662]
 [178121.63787662]
 [180408.6378916 ]]

predicted response with OverallCond as input: 
[[178066.64310354]
 [178066.64310354]
 [179579.40110694]
 ...
 [177445.18201695]
 [179579.40110694]
 [179579.40110694]]

